spring.application.name=aipowered-location-advisor

#Server Configuration
server.port=1010

#Livereload Configuration
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false