spring.application.name=aipowered-location-advisor

#Server Configuration
server.port=1010
server.address=localhost
server.servlet.context-path=/v1/api

#Livereload Configuration
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

#Database Configuration
spring.data.mongodb.database=${env.MONGO_DB}
spring.data.mongodb.uri=mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}

#Logging Configuration
logging.level.org.mongodb.driver=warn

#OpenAI Configuration
spring.ai.openai.api-key=${env.OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-2024-11-20
spring.ai.openai.chat.options.temperature=0.2

#Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${env.EMAIL_SENDER}
spring.mail.password=${env.EMAIL_SENDER_PW}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true